export const replayMcpTools = [
  "RecordingOverview",
  "ConsoleMessages",
  "DescribePoint",
  "Evaluate",
  "GetStack",
  "GetPointComponent",
  "InspectElement",
  "LocalStorage",
  "Logpoint",
  "NetworkRequest",
  "ReactComponentTree",
  "ReactRenders",
  "UserInteractions",
  "ReduxActions",
  "ZustandStores",
  "TanStackQueries",
  "ReactException",
  "UncaughtException",
  "ListSources",
  "ReadSource",
  "SearchSources",
  "ExecutionDelay",
  "GetPointLink",
  "Screenshot",
  "PlaywrightSteps",
  "ProfileStatements",
  "ProfileSampling",
  "ProfileGraph",
];

export const labScenarios = [
  {
    id: "happy-path",
    kind: "passing",
    testFile: "tests/passing/happy-path.spec.ts",
    toolsCovered: [
      "RecordingOverview",
      "Screenshot",
      "GetPointLink",
      "PlaywrightSteps",
      "ConsoleMessages",
      "NetworkRequest",
      "LocalStorage",
      "UserInteractions",
    ],
  },
  {
    id: "state-react",
    kind: "passing",
    testFile: "tests/passing/state-react.spec.ts",
    toolsCovered: [
      "DescribePoint",
      "Evaluate",
      "GetStack",
      "GetPointComponent",
      "ReactComponentTree",
      "ReactRenders",
      "ReduxActions",
      "ZustandStores",
      "TanStackQueries",
    ],
  },
  {
    id: "dom-layout",
    kind: "passing",
    testFile: "tests/passing/dom-layout.spec.ts",
    toolsCovered: ["InspectElement", "Screenshot", "ReactComponentTree"],
  },
  {
    id: "source-logpoint",
    kind: "passing",
    testFile: "tests/passing/source-logpoint.spec.ts",
    toolsCovered: [
      "ListSources",
      "ReadSource",
      "SearchSources",
      "Logpoint",
      "DescribePoint",
      "Evaluate",
      "GetStack",
      "ExecutionDelay",
      "GetPointLink",
    ],
  },
  {
    id: "runtime-exception",
    kind: "diagnostic-failure",
    testFile: "tests/failures/runtime-exception.spec.ts",
    toolsCovered: ["UncaughtException", "ConsoleMessages", "GetStack", "ReadSource"],
  },
  {
    id: "react-exception",
    kind: "diagnostic-failure",
    testFile: "tests/failures/react-exception.spec.ts",
    toolsCovered: ["ReactException", "ReactComponentTree", "ReactRenders", "ReadSource"],
  },
  {
    id: "playwright-failure",
    kind: "diagnostic-failure",
    testFile: "tests/failures/playwright-failure.spec.ts",
    toolsCovered: ["PlaywrightSteps", "Screenshot", "ConsoleMessages"],
  },
  {
    id: "profiling",
    kind: "passing",
    testFile: "tests/passing/profiling.spec.ts",
    toolsCovered: ["ProfileStatements", "ProfileSampling", "ProfileGraph", "ExecutionDelay"],
  },
];
